### ISSUE TITLE
Support mutations

### ISSUE THREAD

**Issue by cdroulers** [ckimes89/graphql-net#16] opened 2016-04-13 17:44 UTC
Hey guys!

Just started looking into GraphQL and your project looks great! I was wondering if there were short term plans for mutation support. I'm looking into creating a project that would do CQRS via GraphQL and this framework looks good but lacks mutation for now!

**Comment by ckimes89** [comment] 2016-04-13 18:54
Thanks for the issue!

Mutations are definitely in the plans, though I've been thinking about the best way to represent them in the API. There are a few changes to the current API that we've also been planning since all the additional features we want to add won't fit easily into the current Fluent interface.

However, if you're eager to try the library I can probably get rudimentary mutation support working before the end of the week. I should note that this is definitely still an alpha version so the API may change significantly between releases.

**Comment by cdroulers** [comment] 2016-04-13 19:34
There's no rush for mutations. I'm starting with querying first and will end up with mutations in two or three weeks.

I already assumed this was alpha with the quantity of commits coming in!

**Comment by ckimes89** [comment] 2016-06-29 15:38
Hey Andy,

I apologize that development of this project has slowed recently as I've
gotten busy with other things. I do have a pretty good idea of how I want
to handle mutations, I just need to get some time in front of the keyboard
to do it.

I'll work on getting mutations implemented within the next few days and
then push a new version to NuGet.

-Chad

**Comment by ckimes89** [comment] 2016-06-30 00:42
Mutations have landed (in dev)!

The API is similar to the explicit query API. This is pretty much a requirement since we have to specify both a name and an explicit argument shape. I'll copy an example from the tests for this feature:

```csharp
schema.AddMutation("mutate",
    new {id = 0, newVal = 0},
    (db, args) => db.MutateMes.AsQueryable().FirstOrDefault(a => a.Id == args.id),
    (db, args) =>
    {
        var mutateMe = db.MutateMes.First(m => m.Id == args.id);
        mutateMe.Value = args.newVal;
        db.SaveChanges();
    });
```

Going through it one by one, the first line specifies the name. The second specifies the shape of the arguments (used in the `(db, args)` functions). The third line is the query that will be executed after the mutation is completed. The fourth line(s) is the actual mutation, which is just a function to be executed given the Context and your arguments as parameters.

It's unfortunate that in this case (and I think probably in many others) that the query to be executed is an exact duplicate of an already defined query. I'm considering ways to improve that, but it's a bit difficult given that the arguments shape for a mutation is unlikely to be reused.

**Comment by andyroper** [comment] 2016-06-30 07:25
Excellent - Thanks!

**Closed** 2016-07-31 18:21 UTC
